server:
  port: 8083

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_server?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
